version: '3.8'

services:
  twitter-app:
    container_name: twitter-app
    build: .
    volumes:
      - ./twitter-app:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=twitter-app
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql_db
